language: r
r:
  - release
sudo: false
cache:
  packages: true
  directories:
    - $HOME/.npm
    - $HOME/texlive

git:
  depth: 5
  submodules: false

pandoc_version: 2.2.1

r_github_packages: 
  - tidyverse/ggplot2
  - rstudio/r2d3
  - renozao/RcppOctave


addons:
  apt:
    sources:
      - sourceline: ppa:octave/stable
    packages:
      - ghostscript
      - imagemagick
      - optipng
      - libwebp-dev
      - octave
      - liboctave-dev

before_install:
  - npm install netlify-cli -g
  - tlmgr update --all
  - tlmgr install $(cat TeXLive.pkgs | tr '\n' ' ') || true

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

# deploy 
after_success:
  - netlify deploy -t $NETLIFY_PAT
