language: r
r:
  - 3.5.0
dist: trusty
sudo: false
cache:
  packages: true
  directories:
    - $HOME/texlive

pandoc_version: 2.1.3

addons:
  apt:
    packages:
      - ghostscript
      - imagemagick
      - optipng

before_install:
  # for pdf output
  - tlmgr update --all --self
  - tlmgr install ctex xecjk zhnumber fandol filehook lm-math unicode-math index sourceserifpro

script:
  - Rscript -e 'update.packages(ask = FALSE)'
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'
