language: r
r:
  - 3.5.0
dist: trusty
sudo: false
cache:
  packages: true
  directories:
    - $HOME/texlive

pandoc_version: 2.1.3

addons:
  apt:
    packages:
      - ghostscript
      - imagemagick
      - optipng

before_install:
  - git config --global user.email "xiangyunfaith@outlook.com"
  - git config --global user.name "Xiangyun Huang"
  # for pdf output
  #- tlmgr update --all --self
  - tlmgr install ctex xecjk zhnumber fandol filehook lm-math unicode-math index sourceserifpro

script:
  # - Rscript -e 'update.packages(ask = FALSE)'
  - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "all")'

after_success:
  - cd docs
  - git init
  - git remote add origin https://github.com/XiangyunHuang/notesdown.git
  - git add -A
  - git commit -m"Daily update"
  - git push -q https://${GITHUB_PAT}@github.com/XiangyunHuang/notesdown.git master:cos-docs
 
