# 绪论 {#intro}

## 研究意义

在热带地区，淋巴丝虫病和盘尾丝虫病（河盲病）是严峻的公共卫生问题， 据世界卫生组织统计，在非洲撒哈拉以南、阿拉伯半岛和南美洲的34个国家约2000 $\sim$ 4000万人感染河盲病[@Takougang2002Rapid]。 例如，喀麦隆中部省份，Loa loa （导致河盲病的寄生虫）感染强度与疾病流行度之间存在线性关系，即 Loa loa 流行度越高感染强度越大[@Boussinesq2001]。1997年，研究表明 Loa loa 流行度对应的高感染强度的临界值为 20\%[@Gardon1997Serious]。而研究个体水平的感染情况与群体水平流行度之间的关系有助于大规模给药[@Schl2016Using]。 

## 选题背景

空间广义线性混合效应模型（以下简称SGLMM模型）在地质统计中有着广泛的应用， 如来自有限气象站点的污染物浓度测量， 岩心样本的石油含量的评估，核污染浓度的空间分布[@Diggle1998]， 冈比亚儿童的疟疾流行度的空间分布[@Diggle2002]，喀麦隆及其周边地区的热带眼线虫流行病的的空间分布[@Diggle2007ATMP]， 以及对LFOEP项目（即Lymphatic Filariasis and Onchocerciasis Elimination Programs）的决策支持[@Schl2016Using]， Diggle 和 Giorgi 于2016年在SGLMM模型的基础上进行扩展，以适应三类新的调查数据，其一是组合随机调查数据和非随机调查数据（即潜在有偏的数据）， 以肯尼亚疟疾流行数据为例， 组合了学校和社区的调查数据； 其二是时空扩展， 将时间因素考虑进模型， 以马拉维2010年5月至2013年6月的疟疾流行数据为例； 其三是混合分布， 考虑响应变量是混合二项分布的情况[@Diggle2016]， 检验环境和基因效应在空间相关性中的存在性 [@spaMM2014]， 流行现象的时空分析[@surveillance2017]。 

## 文献综述

地质统计这个术语最初来自南非的采矿业[@Krige1951]， 并由 Georges Matheron 及其同事继承和发展，用以预测矿藏含量和质量。 空间广义线性混合效应模型在这个地统计领域内通常又叫广义线性地统计模型。 地质统计因其包含的广泛科学内容， 逐渐被接受为空间统计的三大主流分支之一， 其余两个是离散空间变差（discrete spatial variation）和空间点过程（spatial point processes）[@Cressie1993]。 1994 年 Geyer 证明了蒙特卡罗最大似然（简称 MCML）积分的收敛性[@Geyer1994On]，1998 年 Diggle 等人提出基于贝叶斯的空间统计方法应用于地质统计领域，分析了南太平洋岛上的核残留的情况，北拉纳克郡和南坎布里亚郡的弯曲杆菌感染情况[@Diggle1998]。 随后，似然估计的统计性质和随机模拟算法的收敛性成为研究的重点： 2002年 Zhang 重点分析了空间广义线性混合效应模型的参数估计和模型预测的计算问题， 应用 MCML [@Zhang2002On] 算法求解模型； 2004年 Christensen 将 MCML 方法应用于朗格拉普岛的数据分析[@Christensen2004]。近年来，在大数据的背景下， 寻求高效的算法成为一个新的方向，2009 年 Rue 等人提出基于近似贝叶斯推断的集成嵌套拉普拉斯算法，简称 INLA[@INLA2009]， 并将其应用于空间数据建模[@INLA2015]，还推广到一般的贝叶斯计算[@INLA2017]。2016 年 Bonat 和 Ribeiro Jr. 综合比较了 MCML、贝叶斯 MCMC 和 INLA 方法[@Bonat2016Practical]。 同时， 涉及空间数据分析和建模的书籍也越来越多， 用于空间数据分析的分层模型[@Banerjee2015]和基于 `R-INLA` 软件的空间和时空贝叶斯模型 [@Blangiardo2015]。

## 论文结构

第\@ref(intro)章介绍论文相关背景，研究现状；第\@ref(models)章回顾了一般线性模型到广义线性混合效应模型的发展和模型结构；第\@ref(algorithms)章介绍了求解空间广义线性混合效应模型的算法及相关软件实现的技术路线；第\@ref(simulations) 章展示算法模拟的结果；第\@ref(applications)章给出基于SGLMM建模的案例分析；第\@ref(summary)章给出全文总结和展望。
