# 基础图形 {#graphics}

```{r setup, include = FALSE}
Pkgs <- c(
  "cranlogs", "ggthemes", "webp", "rsvg",
  "pdftools", "magick",
  "ISLR",
  "tidyverse","ggrepel",
  "leaflet","rbokeh","plotly","highcharter"
)
if (length(setdiff(Pkgs, .packages(TRUE))) > 0) {
  install.packages(setdiff(Pkgs, .packages(TRUE)))
}

if (!"spDataLarge" %in% .packages(TRUE)) {
  install.packages("spDataLarge",
    repos = "https://nowosad.github.io/drat/",
    type = "source"
  )
}
```

## plot {#base}

```{r run-length-hist, fig.cap='游程直方图', fig.showtext=TRUE}
set.seed(2018) 
n <- 2^16
x <- runif(n,0,1)
delta <- 0.01
len <- diff(c(0,which(x < delta),n+1))-1
ylim <- seq( 0, 1800, by = 300)
xlim <- seq( 0, 100, by = 20)
p <- hist(len[len < 101], breaks = -1:100+0.5, plot = FALSE)
par(mar = c(2,2,.5,.5))
plot(p, xlab = '间距', ylab = '频数', axes = FALSE, 
     col = "lightblue", border = "white", main = "")	 
axis( 1, labels = xlim, at = xlim, las = 1) # x 轴
axis( 2, labels = ylim, at = ylim, las = 0) # y 轴
box(col="gray")
# 添加线性回归线
xx <- seq.int(from = 0, to = 100, by = 1)
xy <- p$counts
options(digits = 2)
fit <- lm(xy~xx)
abline(fit, col = 'red')
b = coef(fit)
# mtext(paste0( "Y = ", paste0(paste0(b[1], b[2]),"x") ), side = 3, cex = 2)
```

还你一个清爽的世界，统计之都文章 [漫谈条形图](https://cosx.org/2017/10/discussion-about-bar-graph/)

```{r beautiful-barplot,fig.cap="条形图"}
data(NCI60, package = "ISLR") # 加载数据
myData <- sort(table(NCI60$labs), decreasing = TRUE)
par(mar = c(2, 7, 1, 1))
barCenters <- barplot(myData,
  col = "lightblue", axes = FALSE,
  axisnames = FALSE, horiz = TRUE, border = "white"
)
text(
  y = barCenters, x = par("usr")[3],
  adj = 1, labels = names(myData), xpd = TRUE
)
axis(1, labels = seq(0, 9, by = 1), at = seq(0, 9, by = 1), las = 1, col = "gray")
```

plot 作为一个泛型函数，对于不同的输入数据类型，会自动匹配不同的绘图函数，默认的有

```{r}
methods(plot)
```


```{r nice-plot, fig.cap='丰富的方法', fig.width=8,fig.height=9,out.width="80%"}
op <- par(mfrow = c(3, 2), mar = c(2, 2, .5, .5))
# 分类散点图
plot(Sepal.Length ~ Sepal.Width, data = iris, col = Species, pch = 16)
legend("topright",
  legend = unique(iris$Species), box.col = "gray",
  pch = 16, col = unique(iris$Species)
)
box(col = "gray")
# 气泡图
plot(Volume ~ Height,
  data = trees, pch = 16, cex = Girth / 8,
  col = rev(terrain.colors(nrow(trees), alpha = .5))
)
box(col = "gray")
# 折线图
plot(AirPassengers, col = "lightblue")
box(col = "gray")

# 柱形图
set.seed(123456)
barPois <- table(stats::rpois(1000, lambda = 5))
plot(barPois, col = "lightblue", type = "h", lwd = 10, main = "")
box(col = "gray")

# 马赛克图
# par(mar=c(2,2,.5,.5))
plot(HairEyeColor, col = "lightblue", border = "white", main = "")
# box(col="gray")
# 矩阵图 自带 layout
plot(iris[, -5], col = iris$Species, pch = 16)
par(op)
```

raster 图形

```{r, fig.cap="raster 图形"}
library(raster)
library(sp)
library(spDataLarge)
plot(elevation, asp = NA)
```

注意与 image 函数区别

```{r, fig.cap="image 图形"}
# A prettier display of the volcano
x <- 10*(1:nrow(volcano))
y <- 10*(1:ncol(volcano))
image(x, y, volcano, col = terrain.colors(100), axes = FALSE)
contour(x, y, volcano, levels = seq(90, 200, by = 5),
        add = TRUE, col = "peru")
axis(1, at = seq(100, 800, by = 100))
axis(2, at = seq(100, 600, by = 100))
box()
title(main = "Maunga Whau Volcano", font.main = 4)
```
