# 书签 {#bookmarks}

## 主页 {#homepage}

- [Eugene Joh 的博客](https://incidental-ideas.org/)
- [Ilya Kashnitsky 的博客](https://ikashnitsky.github.io/)
- [Max Woolf 的博客](http://minimaxir.com/)
- [Yan Holtz 的 ggplot2 图库](https://www.r-graph-gallery.com/)
- [Jianghao Wang (王江浩)](https://jianghao.github.io)
- [Xinpeng Chen](https://chenxinpeng.github.io/)
- [Arthur Charpentier](https://freakonometrics.github.io) 法语 精算 or [Arthur Charpentier](https://freakonometrics.hypotheses.org)
- [François Husson](https://francoishusson.wordpress.com/) 多元统计分析
- [Jean-Paul Fox](http://www.jean-paulfox.com/) Bayesian response modeling
- [Julian faraway](https://farawaystatistics.wordpress.com) INLA [When Small Data beats Big Data](http://people.bath.ac.uk/jjf23/papers/smallvbig.pdf)

- [Yihui Xie](https://yihui.name/)
- [Beilei Bian](http://statsjoke.me)
- [Miao Yu](https://yufree.cn/)
- [Ce Gao](http://gaocegege.com/Blog/)
- [Lchiffon](http://langdawei.com/)
- [Nan Xiao](https://nanx.me/)
- [Xuening Zhu](https://xueningzhu.github.io/)
- [Guangchuang YU](https://guangchuangyu.github.io/)
- [Qiang Kou](http://qkou.info/)
- [Yixuan Qiu-cn](https://yixuan.cos.name/cn/) or [Yixuan Qiu-en](https://statr.me/)
- [Tao Gao](https://joegaotao.github.io/)
- [Xunmo Yang](https://tcya.xyz/)
- [Yalei Du](http://yalei.name/)
- [Junchen Feng](http://www.fengjunchen.com/)
- [Sizhe Liu](http://www.bjt.name/)
- [Liyun Chen](http://www.loyhome.com/)

## 博客 {#blogger}

- [利用 R 和 OpenCPU 搭建高可用的 HTTP 服务](http://www.bjt.name/2017/04/opencpu-application)
- [Nearest Neighbor Gaussian Processes (NNGP) based models](https://github.com/LuZhangstat/NNGP_STAN) and [Case study: NNGP based models in Stan](http://mc-stan.org/users/documentation/case-studies/nngp.html)
- [Spatial Models in Stan: Intrinsic Auto-Regressive Models for Areal Data](http://mc-stan.org/users/documentation/case-studies/icar_stan.html) 空间模型之 Stan 实现 [slides](https://github.com/stan-dev/stancon_talks/blob/master/2018/Invited-Talks/Morris.pdf)
- [Easily Make Multi-tabbed .xlsx Files with openxlsx](https://trinkerrstuff.wordpress.com/2018/02/14/easily-make-multi-tabbed-xlsx-files-with-openxlsx/) Map 函数
- [Deep learning at rstudio::conf 2018](https://rviews.rstudio.com/2018/02/14/deep-learning-rstudio-conf-2018/) 深度学习与R语言,J.J.作为 RStudio 的 CEO 推动 tensorflow 在 R 中的使用，两个幻灯片值得好好看，J.J. 介绍 tensorflow Javier Luraschi介绍tf的部署
- netlify travis-ci blog 搭建 blogdown <https://bookdown.org/yihui/blogdown>
- [An Introduction to Spatial Econometrics in R](http://www.econ.uiuc.edu/~lab/workshop/Spatial_in_R.html) spatial econometric analysis 空间经济分析 可考虑翻译一下 <https://ignaciomsarmiento.github.io/2017/02/07/An-Introduction-to-Spatial-Econometrics-in-R>
- [Data Visualization Shiny Apps](https://ignaciomsarmiento.github.io/software.html) 数据可视化核密度估计 In this app I identify crime hotspots using a bivariate density estimation strategy
- [Putting the Macron in Māori: Accented text in R Graphics](https://www.stat.auckland.ac.nz/~paul/Reports/maori/maori.html) Paul Murrell 图形中嵌入重音字符
- [color in plot](https://www.stat.auckland.ac.nz/~paul/Talks/colour.pdf) Paul Murrell 配色
- [Using Computer Modern Fonts in R Graphics](https://www.stat.auckland.ac.nz/~paul/R/CM/CMR.html) Paul Murrell 图形中嵌入数学字体
- [Lattice Graphics](https://www.stat.auckland.ac.nz/~paul/Talks/dsc2001.pdf) Paul Murrell 介绍 Lattice Graphics
- [Association of Statisticians of American Religious Bodies (ASARB) viridis USA map](http://www.rpubs.com/cgarey/ProjectOneFinal)
- [Mapping unemployment data](http://sharpsightlabs.com/blog/map-unemployment-nov-2016/)
- [when-will-evolution-outperform-local-search](https://blog.evorithmics.org/2016/01/31/when-will-evolution-outperform-local-search/) 进化何时跑赢局部搜索 爱可可爱生活--进化如何跑赢局部搜索
- [Game of Thrones network analysis](https://shirinsplayground.netlify.com/2018/03/got_network/) 权利的游戏 网络
- [Using Git and GitHub with R, Rstudio, and R Markdown](https://github.com/jennybc/happy-git-with-r)
- [如何用Markdown写论文](http://blog.sciencenet.cn/blog-377709-1088215.html)

- [The R-INLA project and Bayesian computing with INLA](http://www.r-inla.org/)
- [Geographic Data Science in Python](https://data.cdrc.ac.uk/dataset/geographic-data-science-in-python)
- [Spatial](https://data.cdrc.ac.uk/)
- [r-spatial](https://www.r-spatial.org/)
- [Fast GeoSpatial Analysis in Python](http://matthewrocklin.com/blog/work/2017/09/21/accelerating-geopandas-1)
- [Spatial Data in R: New Directions](https://edzer.github.io/UseR2017/) Edzer Pebesma
- [A gentle INLA tutorial](https://www.precision-analytics.ca/blog-1/inla)


## 书单 {#books}

- [Pro Git 中文第二版](https://git-scm.com/book/zh/v2) Scott Chacon, Ben Straub 著
- [Advanced R 第二版](https://adv-r.hadley.nz/) Hadley Wickham 著
- [Geocomputation with R](https://geocompr.robinlovelace.net/) Robin Lovelace, Jakub Nowosad, Jannes Muenchow 著
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) Yihui Xie, J. J. Allaire, Garrett Grolemund 著
- [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/) Yihui Xie 著
- [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/) Yihui Xie, Amber Thomas, Alison Presmanes Hill 著
- [R: A Language and Environment for Statistical Computing](https://xiangyun.netlify.com/pdf/refman.pdf) The R Core Team 著
- [LaTeX2e unofficial reference manual](http://tug.ctan.org/tex-archive/info/latex2e-help-texinfo/latex2e.html) [pdf 版](https://xiangyun.netlify.com/pdf/latex2e.pdf)

- [Statistical Rethinking](http://xcelab.net/rm/statistical-rethinking/)  Richard McElreath 著
- [Regression Modeling Strategies](http://biostat.mc.vanderbilt.edu/wiki/Main/RmS) Frank E Harrell Jr 著
- [Applied Predictive Modeling](http://appliedpredictivemodeling.com/) Max Kuhn and Kjell Johnson 著
- [Forecasting: Principles and Practice](https://www.otexts.org/fpp2/) Rob J Hyndman and George Athanasopoulos 著


> 此节附录最后可以删掉

下面是用一段 Python 代码导出谷歌浏览器的所有书签

```bash
python py-chrome-bookmarks-markdown.py bookmarks.md
```

**Optimization**

- [Hyperparameter Optimization in H2O: Grid Search, Random Search and the Future – H2O blog](http://blog.h2o.ai/2016/06/hyperparameter-optimization-in-h2o-grid-search-random-search-and-the-future/)
- [R Optimization Test - Quantitative Finance Collector](http://www.mathfinance.cn/r-optimization-test/)
- [Research Seminar: Optimization](http://statmath.wu.ac.at/courses/optimization/)
- [Home - Statistics Views](http://www.statisticsviews.com/view/index.html)
- [Vasicek model - Wikiwand](https://www.wikiwand.com/en/Vasicek_model)
- [CIR模型Cox–Ingersoll–Ross model - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Cox%E2%80%93Ingersoll%E2%80%93Ross_model)
- [BARON Software | Sahinidis](http://archimedes.cheme.cmu.edu/?q=baron)
- [竞赛列表-DataCastle大数据竞赛平台](http://www.pkbigdata.com/static_page/cmpList.html)
- [COIN-OR: Computational Infrastructure for Operations Research | Open-source Software for the Operations Research Community](https://www.coin-or.org/)
- [Portfolio Optimization in R, Part 4 | R-bloggers](https://www.r-bloggers.com/portfolio-optimization-in-r-part-4/)

**时间序列分析**

- [TensorFlow for Foreign Exchange Market: Analyzing Time-Series Data - Blog on All Things Cloud Foundry](https://blog.altoros.com/tensorflow-for-foreign-exchange-market-analyzing-time-series-data.html)
- [Predicting Heavy and Extreme Losses in Real-Time for Portfolio Holders (2) | Quant at Risk](http://www.quantatrisk.com/2015/12/06/predicting-heavy-and-extreme-losses-in-real-time-for-portfolio-holders-2/)
- [Why time series forecasts prediction intervals aren't as good as we'd hope](http://ellisp.github.io/blog/2016/12/07/arima-prediction-intervals)
- [Error, trend, seasonality - ets and its forecast model friends](http://ellisp.github.io/blog/2016/11/27/ets-friends)
- [Dual axes time series plots with various more awkward data](http://ellisp.github.io/blog/2016/08/28/dualaxes2)

R 语言

- [Togaware – Resources for the Data Scientist](https://togaware.com/)
- [ParallelR高性能并行计算与R语言](http://www.parallelr.com/)
- [R-Ladies global tour ](http://www.masalmon.eu/2017/10/06/globalrladiestour/)
- [R-Ladies Global – R-Ladies is a world-wide organization to promote gender diversity in the R community](http://rladies.org/)
- [Shane Lynn - Data science, analytics, and Startups](https://www.shanelynn.ie/)
- [Open Source Projects | NumFOCUS](https://www.numfocus.org/open-source-projects/)
- [DataScience+ An online community for showcasing R & Python tutorials](https://datascienceplus.com/)
- [Latest Posts – So Simple Theme](https://mmistakes.github.io/so-simple-theme/)
- [Video Tutorial of PSO implementation in MATLAB](http://yarpiz.com/440/ytea101-particle-swarm-optimization-pso-in-matlab-video-tutorial)
- [Statistics.com - Course List - Online Courses](http://www.statistics.com/course-catalog/)
- [me nugget](http://menugget.blogspot.jp/)
- [Time Series Analysis and Its Applications: With R Examples - tsa4](http://www.stat.pitt.edu/stoffer/tsa4/)
- [(code实战)机器学习方法和性能比较](http://rpubs.com/m3cinc/Benchmarking_20_Machine_Learning_Models_Accuracy_and_Speed)
- [ggplot2 – The R graph Gallery](http://www.r-graph-gallery.com/portfolio/ggplot2-package/)
- [quantumobject/docker-shiny - Docker Hub](https://hub.docker.com/r/quantumobject/docker-shiny/)
- [ggplot2绘图库](http://www.sthda.com/english/)
- [Highcharter 商业](http://jkunst.com/highcharter/)
- [john-coene.com](http://john-coene.com/)
- [Large File Support in Linux](http://users.suse.com/~aj/linux_lfs.html)
- [Deep Learning in R – R Blog](http://www.rblog.uni-freiburg.de/2017/02/07/deep-learning-in-r/)
- [Zelig 统计推断方法合集](https://zeligproject.org/)
- [Paul Murrell's Home Page](https://www.stat.auckland.ac.nz/~paul/)
- [Data Science Accelerator for Credit Risk Prediction (Revolutions)](http://blog.revolutionanalytics.com/2017/07/credit-risk-prediction.html)
- [Credit Card Fraud Detection | Kaggle](https://www.kaggle.com/dalpozz/creditcardfraud)

**Python**

- [Jupyter Notebook Viewer](http://nbviewer.jupyter.org/)
- [Pyomo](http://www.pyomo.org/)
- [Bokeh Docs](http://bokeh.pydata.org/en/latest/)
- [NumPy Tutorial: Data analysis with Python](https://www.dataquest.io/blog/numpy-tutorial-python/)
- [scikit-learn: machine learning in Python — scikit-learn 0.18.1 documentation](http://scikit-learn.org/stable/)
- [Introduction to NumPy and Matplotlib - YouTube](https://www.youtube.com/watch?v=3Fp1zn5ao2M&feature=plcp)
- [Data Science, Analytics and Big Data discussions](https://discuss.analyticsvidhya.com/)
- [The Python Graph Gallery – Visualizing data – with Python](https://python-graph-gallery.com/)
- [Data science, data analysis, and data engineering tutorials and articles.](https://www.dataquest.io/blog/)
- [ŷhat | Image Processing with scikit-image](http://blog.yhat.com/posts/image-processing-with-scikit-image.html)

**社交网络**

- [Using the iGraph package to Analyse the Enron Corpus](http://r.prevos.net/analyse-enron-corpus/)
- [Help Us Map TrumpWorld](https://www.buzzfeed.com/johntemplon/help-us-map-trumpworld?utm_term=.rx9NY9Ldb#.ja8P4p9LY)
- [Enron Email Dataset](https://www.cs.cmu.edu/~./enron/)
- [Statnet](http://statnet.org/)
- [Mining Twitter with R](https://sites.google.com/site/miningtwitter/)
- [graphTweets](http://john-coene.com/packages/graphTweets/)
- [Building Wordclouds in R | DataScience+](https://datascienceplus.com/building-wordclouds-in-r/)
- [API - 微博API](http://open.weibo.com/wiki/API%E6%96%87%E6%A1%A3_V2?sudaref=jianl.org&retcode=6102)
- [Introducing tidygraph](http://www.data-imaginist.com/2017/Introducing-tidygraph/)
- [Network analysis of Game of Thrones | DataScience+](https://datascienceplus.com/network-analysis-of-game-of-thrones/)
- [Using R packages and education to scale Data Science at Airbnb – Airbnb Engineering & Data Science – Medium](https://medium.com/airbnb-engineering/using-r-packages-and-education-to-scale-data-science-at-airbnb-906faa58e12d)
- [RPubs - Twitter Coverage of the ISMB/ECCB Conference 2017](http://rpubs.com/neilfws/295865)
- [UCI Network Data Repository](https://networkdata.ics.uci.edu/)

**课程**

- [DS-GA 1003: Machine Learning and Computational Statistics, Spring 2015](http://davidrosenberg.github.io/ml2015/#home)
- [卡内基梅隆大学Machine Learning课程](http://www.cs.cmu.edu/~tom/10701_sp11/hws.shtml)
- [课程列表: Deep Learning](http://eclass.cc/courselists/117_deep_learning)
- [(概率图模型-卡内基梅隆大学) Probabilistic Graphical Models](http://www.cs.cmu.edu/~epxing/Class/10708/lecture.html)
- [Learning Deep Learning课程资料大集合](http://rt.dgyblog.com/ref/ref-learning-deep-learning.html)
- [课程Theoretical Machine Learning](http://www.cs.princeton.edu/courses/archive/spring14/cos511/schedule.html)
- [机器学习算法观](http://people.csail.mit.edu/moitra/409.html)
- [(伯克利大学)机器学习导论课程Introduction to Machine Learning](http://www.cs.berkeley.edu/~jrs/189/)
- [Intro to Apache Spark Training - Part 3 - YouTube](https://www.youtube.com/watch?v=Cxv_ERVKYE4)
- [李宏毅深度学习(2017)_演讲•公开课_科技_bilibili_哔哩哔哩](http://www.bilibili.com/video/av9770302/)
- [1.1 《机器学习中的神经网络》为什么我们需要机器学习？_腾讯视频](https://v.qq.com/x/page/t0384c1p2em.html)
- [In-depth introduction to machine learning in 15 hours of expert videos](http://www.dataschool.io/15-hours-of-expert-machine-learning-videos/)
- [Gephi 中文教程 | Udemy](https://www.udemy.com/gephi/learn/v4/overview)

**Deep Learning**

- [PyTorch](http://pytorch.org/)
- [Caffe 2 | Caffe2](https://caffe2.ai/)
- [[福利] 深入理解 RNNs & LSTM 网络学习资料 - 简书](http://www.jianshu.com/p/c930d61e1f16?from=timeline)
- [TensorFlow中文社区-首页](http://tensorfly.cn/)
- [Deep Learning in Energy Production context (wind, gas and oil)](https://amundtveit.com/)
- [Off the convex path](http://www.offconvex.org/)
- [The Neural Network Zoo - The Asimov Institute](http://www.asimovinstitute.org/neural-network-zoo/)
- [Yann LeCun's Home Page](http://yann.lecun.com/)
- [Yoshua Bengio](http://www.iro.umontreal.ca/~bengioy/yoshua_en/index.html)
- [Ian Goodfellow --- Research Page](http://www.iangoodfellow.com/)
- [Time Series Prediction With Deep Learning in Keras - Machine Learning Mastery](http://machinelearningmastery.com/time-series-prediction-with-deep-learning-in-python-with-keras/)
- [迁移学习 Keras R](https://flovv.github.io/Logo_detection_transfer_learning/)
- [Information Systems Research](https://www.is.uni-freiburg.de/)
- [The Ultimate List of TensorFlow Resources: Books, Tutorials & More - Hacker Lists](https://hackerlists.com/tensorflow-resources/)
- [Neural Networks from Scratch, in R (Revolutions)](http://blog.revolutionanalytics.com/2017/07/nnets-from-scratch.html)
- [[机器学习入门] 李宏毅机器学习笔记](http://blog.csdn.net/soulmeetliang)
- [Center for Machine Learning and Intelligent Systems | University of California, Irvine](http://cml.ics.uci.edu/)
- [(支持向量机算法)LIBSVM -- A Library for Support Vector Machines](http://www.csie.ntu.edu.tw/~cjlin/libsvm/)

**软件测试**

- [Jenkins](https://jenkins.io/)
- [Centos | Docker中文教程](https://letong.gitbooks.io/docker/content/install/centos.html)
- [Ubuntu – Ubuntu Packages Search](https://packages.ubuntu.com/)
- [Pandoc - Pandoc User’s Guide](http://pandoc.org/MANUAL.html#pandocs-markdown)

**LaTeX**

- [始终](https://liam0205.me/)
- [风陵渡](http://wangmurong.org.cn/)
- [fitsir的博客](https://fitsir.me/)
- [Ethlisan | Ethan DENG's Personal Homepage](http://ddswhu.com/)
- [Cyberspace of Shujun LI李树钧](http://www.hooklee.com/)
- [LaTeX写作专栏 – |经常|](http://blog.feieee.com/latex)
- [在线 LaTeX 公式编辑器](http://www.codecogs.com/latex/eqneditor.php)
- [Beamer Matrix](https://mpetroff.net/files/beamer-theme-matrix/)
- [ChinaTeX-Tex&LaTeX are your typesetting friends.](http://www.chinatex.org/)
- [LaTeX Templates](http://www.latextemplates.com/)
- [Overleaf](https://www.overleaf.com/)
- [Introduction | Learning-Markdown (Markdown 入门参考)](http://xianbai.me/learn-md/index.html)
- [MathJax | Beautiful math in all browsers.](https://www.mathjax.org/)
- [Pandoc - About pandoc](https://pandoc.org/)
- [TikZ and PGF | TeXample.net](http://www.texample.net/tikz/)
- [Rants from the Lab](http://liantze.penguinattack.org/)

- [国家企业信用信息公示系统](http://www.gsxt.gov.cn/index.html)
- [Linux命令大全(手册)_Linux常用命令行实例详解_Linux命令学习手册](http://man.linuxde.net/)
- [生命不息 | 张宏伦的个人博客](http://zhanghonglun.cn/blog/)
- [大赛列表页](https://tianchi.aliyun.com/competition/gameList.htm)
- [城市数据派-首页](https://www.udparty.com/index.php)
- [研趣网 - 首个可视化商业价值挖掘和传播社区](http://www.rinterest.cn/)
- [inFERENCe](http://www.inference.vc/)
- [MSDN, 我告诉你](http://msdn.itellyou.cn/)
- [RegExr: Learn, Build, & Test RegEx](https://regexr.com/)
- [rud.is | "In God we trust. All others must bring data"](https://rud.is/b/)
- [北京理工大学 开源软件镜像服务](http://mirror.bit6.edu.cn/web/)
- [Statistics authors/titles recent submissions](http://arxiv.org/list/stat/recent)
- [Wolfram|Alpha: Computational Knowledge Engine](http://www.wolframalpha.com/?source=nav)
- [中国科技论文在线](http://www.paper.edu.cn/)
- [我是菜鸟 | IMCN开源资讯网](https://imcn.me/)

- [USGS.gov](https://www.usgs.gov/)
- [Index of /download/ensembles/data/Grid_0.44deg_rot](http://www.ecad.eu/download/ensembles/data/Grid_0.44deg_rot/)
- [The Stan Forums](http://discourse.mc-stan.org/)
- [论坛 - 六维空间 - 教育科研网分享测试平台](http://bt.neu6.edu.cn/forum.php)
- [免费在线电影-新剧集影院官网-支持手机观看](http://www.xinjuji.com/index.html)
- [CCTV-1 综合频道高清直播](http://tv.cctv.com/live/cctv1/)
- [BYR-IPTV](http://tv.byr.cn/tv-show-detail/78)
- [七牛云-国内领先的企业级云服务商](https://www.qiniu.com/)
- [RStudio Community](https://community.rstudio.com/)
- [电影天堂_免费电影_迅雷电影下载](http://www.dytt8.net/)
- [80s电影网 - 高清手机电影迅雷下载_最新MP4电视剧磁力下载](https://www.80s.tw/)
- [Google](https://www.google.com/)
- [gen.lib.rus.ec](http://gen.lib.rus.ec/)
- [Octave Online · Cloud IDE compatible with MATLAB](https://octave-online.net/#cmd=peaks)
