--- 
title: "A Book Example"
author: "黄湘云"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
geometry: margin=1.18in
documentclass: ctexbook
bibliography: [book.bib, packages.bib]
biblio-style: apalike
lof: yes
lot: yes
graphics: yes
tables: yes
link-citations: yes
colorlinks: yes
classoption: "hyperref, a4paper, UTF8, zihao = -4, linespread = 1.3"
description: "这是一个笔记，搜集了很多博客内容"
---

```{r setup, include=FALSE}
source("common.R")
```

\mainmatter

# 前言 {#preface}

咳咳，不知道写什么

## 作者 {#author}

我是黄湘云，硕士

## 致谢 {#intro-ack}

虚位以待壮士

```{r, results = "asis", echo = FALSE}
# copy from https://github.com/hadley/adv-r/edit/master/Introduction.Rmd
# contribs <- system("git --no-pager shortlog -ns > contribs.txt", intern = T)
contribs <- read.delim("contribs.txt", header = FALSE, 
  stringsAsFactors = FALSE)[-1, ]
names(contribs) <- c("n", "name")

contribs <- contribs[order(contribs$name), ]
contribs$uname <- ifelse(!grepl(" ", contribs$name), 
  paste0("\\@", contribs$name), contribs$name)

cat("Thanks go to all contributers in alphabetical order: ")
cat(paste0(contribs$uname, collapse = ", "))
cat(".\n")
```

## 本书结构 {#outline}

第一章：数学符号说明
第二章：基础知识

- R语言基础、高级技巧


## 后记 {#colophon}

这本书是在 RStudio IDE 内用 R Markdown 写的，knitr 和 pandoc 将 R Markdown 转化为 html 和 pdf，这个网站是通过 travis-ci 自动发布到 netlify，完整的源文件存放在 github 上。

> 矢量图片的位置：


## 软件信息 {#session}

系统安装的 R 包有：

```{r}
.packages(TRUE)
```

R 软件运行环境：

```{r}
devtools::session_info()
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(TRUE)
), "packages.bib")
```
