---
title: "Untitled"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
source(file = "../common.R")
knitr::opts_chunk$set(engine.path = list(
  octave = '/usr/bin/octave-cli',
  python = '/usr/bin/python'
))
```

 standard normal distribution (mean = 0, standard deviation = 1)

```{octave}
stdnormal_rnd(1,5)
```

$\mu = 2, \sigma = 4$ standard deviation sigma

```{octave}
%% copy from https://stackoverflow.com/questions/13735096/python-vs-octave-random-generator
function state = mtstate(seed)
state = uint32(zeros(625,1));
state(1) = uint32(seed);
for i=1:623,
   tmp = uint64(1812433253)*uint64(bitxor(state(i),bitshift(state(i),-30)))+i;
   state(i+1) = uint32(bitand(tmp,uint64(intmax('uint32'))));
end
state(625) = 1;
end

rand('state',mtstate(4));
rand(1,5)
rand('state',mtstate(4));
rand(1,5)
```


```{python}
help('modules')
```


```{r tikz-demo, dev='tikz', fig.cap="Linear",fig.showtext=FALSE}
x <- rnorm(10)
y <- x + rnorm(5, sd = 0.25)
model <- lm(y ~ x)
rsq <- summary(model)$r.squared
rsq <- signif(rsq, 4)
plot(x, y, main = "Hello \\LaTeX!", xlab = "$x$", ylab = "$y$", 
     sub = "$\\mathcal{N}(\\mathbf{x};\\mu,\\Sigma)$")
abline(model, col = "red")
mtext(paste("Linear model: $R^{2}=", rsq, "$"), line = 0.5)
legend("bottomright", legend = paste0("$y = ", 
                                     round(coef(model)[2], 3),
                                     "x +", 
                                     round(coef(model)[1], 3), 
                                     "$"
                                     ), 
       bty = "n")
```

```{r latex-tikz, engine='tikz', out.width='90%', fig.ext=if (knitr:::is_latex_output()) 'pdf' else 'png', fig.cap='tikz', engine.opts = list(template = "../tikz/tikz2pdf.tex")}
\begin{tikzpicture}[scale=.7]
\draw [fill=gray!30,very thick] (0,-1) rectangle (5,1);
\draw [very thick] (5, 0) -- (13,0);
\node [below] at (2,-1) {\large Hello};
\node [below, align=center] at (0,-1) {\large Two\\ lines};
\end{tikzpicture}
```