---
title: "Notebook"
output: html_document
---

# Stan 框架

## R 接口实现

```{r}
# 加载 Stan 的 R 接口
library(rstan)  
```

配置 stan 运行参数

```{r}
options(mc.cores = 2) # 两个线程
rstan_options(auto_write = TRUE)
c_light <- c("#DCBCBC")
c_light_highlight <- c("#C79999")
c_mid <- c("#B97C7C")
c_mid_highlight <- c("#A25050")
c_dark <- c("#8F2727")
c_dark_highlight <- c("#7C0000")
```

加载数据

```{r}
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
```

加载模型

```{r}
fit <- stan(file = 'code/stan/8schools.stan', data = schools_dat, 
            iter = 1000, chains = 4, seed = 483892929, refresh = 1200)
```

模型输出

```{r}
print(fit)
```

诊断采样过程

```{r}
# plot(fit)
pairs(fit, pars = c("mu", "tau", "lp__"))
```

 stan 拟合对象的操作

```{r}
la <- extract(fit, permuted = TRUE) # return a list of arrays 
mu <- la$mu 

### return an array of three dimensions: iterations, chains, parameters 
a <- extract(fit, permuted = FALSE) 

### use S3 functions on stanfit objects
a2 <- as.array(fit)
m <- as.matrix(fit)
d <- as.data.frame(fit)

print(fit, digits = 1)

# ------------------------------------------------------------------
```

## Python 实现

基于 python 2.7.5 和 stan 2.17.1.0

安装几个模块

```bash
yum install python2-pip python-devel tkinter
pip install --upgrade pip
pip install pystan matplotlib
```

加载模块

```{python}
import pystan
import numpy as np
import matplotlib.pyplot as plt
schools_code = """
data {
    int<lower=0> J; // number of schools
    real y[J]; // estimated treatment effects
    real<lower=0> sigma[J]; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    real eta[J];
}
transformed parameters {
    real theta[J];
    for (j in 1:J)
        theta[j] = mu + tau * eta[j];
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
}
"""
schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}
sm = pystan.StanModel(model_code=schools_code)
fit = sm.sampling(data=schools_dat, iter=1000, chains=4)
print(fit)
```


```python
# 其他操作
eta = fit.extract(permuted=True)['eta']
np.mean(eta, axis=0)

# 诊断图
plt.show() 
fit.plot()
# 保存图片
fig = plt.gcf() 
fig.set_size_inches(9,15) # 设置图片宽、高
fig.savefig('test.pdf',bbox_inches='tight') # 去掉边空
# 保存为 png  dpi 越大图片越清晰 
fig.savefig('test.png',bbox_inches='tight',dpi = 150)
```

